name: Cypress CI/CD

on:
  push:
    branches:
      - main

jobs:
  cypress:
    name: Cypress Parallelization
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2, 3 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name : Set Cypress Record Env variables from github secrets
        working-directory: ./cypressAutomation
        run: |
          sed -i "s|XXXCYPRESS_RECORD_KEYXXX|${{secrets.CYPRESS_RECORD_KEY}}|g" ".env_cypress"
          cat ".env_cypress"  
      - name: Install Dependencies
        run: npm install
      - name: Cypress Run
        run: |
          npm run production