name: Cypress CI/CD

on:
  push:
    branches:
      - main

jobs:
  cypress:
    name: Cypress Parallelization
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2, 3 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Cypress Run
        run: |
          npx cypress-tags run --browser chrome -e TAGS=\"@sanity\" --env fileConfig=production --record --key $CYPRESS_RECORD_KEY --parallel --group cypress-test    