name: Cypress CI/CD

on:
  push:
    branches:
      - main

jobs:
  cypress:
    name: Cypress Parallelization
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    strategy:
      fail-fast: false
      matrix:
        containers: [ 0, 1, 2, 3, 4 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Cypress Run
        run: |
          npx cypress run --record --key $CYPRESS_RECORD_KEY
    